import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BreadcrumbProvider } from "./components/app-breadcrumb/BreadcrumbProvider";
import { AppSidebar } from "./components/app-sidebar";
import Header from "./components/header";
import Footer from "./components/footer";
import { DialogProvider } from "./components/alert-dialog/dialog-context";
import { SidebarInset, SidebarProvider } from "./shadcn/ui/sidebar";
import { TitleProgress } from "./components/title-progress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <BreadcrumbProvider >
            <SidebarProvider>
              <DialogProvider>
                <AppSidebar />
                <SidebarInset className="flex flex-col h-screen">
                  <Header />
                  <div className="flex flex-col gap-4 p-4 pt-0 grow overflow-hidden">
                    {children}
                  </div>
                  <Footer />
                </SidebarInset>
              </DialogProvider>
            </SidebarProvider>
          </BreadcrumbProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
